name: Deploy LBW-RiskPrediction App to Heroku using Docker

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy Docker Image to Heroku App
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: "."
          dockerfile_name: Dockerfile
          docker_options: ""
          process_type: web
